name: 'Check Deployment Comment for Change Request Number'
description: 'Ensures deployment comments include a change request number.'

outputs:
  valid:
    description: 'Boolean indicating if the comment is valid'
    value: ${{ steps.check_cr.outputs.valid }}
runs:
  using: 'composite'
  steps:
  # - name: Get deployment comment
  #   id: cr_comment
  #   shell: bash
  #   run: |
  #     echo "deployment comment=${{ github.event.head_commit.message }}"
  #     echo "DEPLOY_COMMENT=${{ github.event.head_commit.message }}" >> "$GITHUB_ENV"

  - name: Capture deployment approval comments
    id: capture_comments
    uses: actions/github-script@v6   
    with:
      # github-token: ${{ secrets.PAT }}
      script: |
        const { owner, repo } = context.repo;       
        const response = await github.request('GET /repos/{owner}/{repo}/actions/runs/{runId}/approvals', {
              owner: owner,
              repo: repo,
              runId: context.runId
           });

        console.log(`reponse: ${JSON.stringify(response.data, null, 2)}`);

        if (response.status === 200) {
            const comments = response.data.map(approval => approval.comment);
            console.log(JSON.stringify(comments, null, 2));
            core.setOutput('comments',comments[0]);
        } else {
            console.error(`Failed to fetch approval comments: ${response.status}`);
        }

  - name: Check for Change Request Number
    id: check_cr
    shell: bash
    run: |
      if echo "${{ steps.capture_comments.outputs.comments }}" | grep -qE "CR-[0-9]+"; then
        echo "valid=true" >> "$GITHUB_OUTPUT"
      else
        echo "valid=false" >> "$GITHUB_OUTPUT"
      fi

  - name: Print the valid comment status
    id: Print
    run: echo "valid='${{ steps.check_cr.outputs.valid}}'"
    shell: bash
    
  - name: Fail if Comment is Invalid
    if: ${{ steps.check_cr.outputs.valid == 'false' }}
    shell: bash
    run: |
      echo "Deployment comments does not contain a Change Request number. Aborting deployment."
      exit 1
