name: 'Check Deployment Comment for Change Request Number'
description: 'Ensures deployment comments include a change request number.'

outputs:
  valid:
    description: 'Boolean indicating if the comment is valid'
    value: ${{ steps.check_cr.outputs.valid }}
runs:
  using: 'composite'
  steps:
  # - name: Get deployment comment
  #   id: cr_comment
  #   shell: bash
  #   run: |
  #     echo "deployment comment=${{ github.event.head_commit.message }}"
  #     echo "DEPLOY_COMMENT=${{ github.event.head_commit.message }}" >> "$GITHUB_ENV"

  - name: Capture deployment approval comments
    id: capture_comments
    uses: actions/github-script@v6
    with:
      # github-token: ${{ secrets.PAT }}
      script: |
        const deploymentId = context.payload.deployment.id;
        const comments = await github.rest.issues.listComments({
          owner: context.repo.owner,
          repo: context.repo.repo,
          issue_number: deploymentId,
        });
        console.log(`comments: ${comments}`)

        core.setOutput('comments', comments.data.map(comment => comment.body).join("\n---\n"));


  - name: Check for Change Request Number
    id: check_cr
    shell: bash
    run: |
      if echo "${{ steps.capture_comments.outputs.comments }}" | grep -qE "CR-[0-9]+"; then
        echo "valid=true" >> "$GITHUB_OUTPUT"
      else
        echo "valid=false" >> "$GITHUB_OUTPUT"
      fi

  - name: Print the valid comment status
    id: Print
    run: echo "valid='${{ steps.check_cr.outputs.valid}}'"
    shell: bash
