
# This is a basic workflow to help you get started with Actions

name: Stage Pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ['dev']
    paths-ignore:
      - './github/workflows/sit.yml'
      - './github/workflows/uat.yml'
      - './github/workflows/stage.yml'
     
 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  dev-sync-deploy-verify-job:   
    uses: ./.github/workflows/sync-deploy-verify.yml
    with:
      BRANCH: dev
      PIPELINEID: "1234-dev"
      SHOULD_TRIGGER_PIPELINE: false
