name: Dev Pipeline

on:
  push:
    branches: ['dev']  
  workflow_dispatch:


jobs:
  dev-sync-deploy-verify-job:   
    uses: ./.github/workflows/sync-deploy-verify.yml
    with:
      BRANCH: dev
      PIPELINEID: "1234-dev"
      SHOULD_TRIGGER_PIPELINE: false
