name: Dev Pipeline

on:
  push:
    branches: ['dev']  
  workflow_dispatch:


jobs:

  testSlug:
    runs-on: ubuntu-latest
    steps:
      - run: echo "$GITHUB_REF_SLUG"
          
  dev-sync-deploy-verify-job: 
    needs: [initVariables]  
    uses: ./.github/workflows/sync-deploy-verify.yml
    with:
      BRANCH: dev      
      SHOULD_TRIGGER_PIPELINE: false
    secrets: inherit     