name: Dev Pipeline

on:
  push:
    branches: ['dev']  
  workflow_dispatch:


jobs:
  # initVariables:    
  #   runs-on: ubuntu-latest
  #   outputs:
  #     PIPELINEID: ${{ steps.setvariables.outputs.PIPELINEID }}

  #   steps:
  #     - name: Set Variables
  #       id: setvariables
  #       run: |
  #         if [[ "${{ github.ref }}" == *"dev" ]]; then
  #           echo "::set-output name=PIPELINEID::${{ secrets.DEV_PIPELINEID}}"
  #         elif [[ "${{ github.base_ref }}" == *"sit" ]]; then
  #           echo "::set-output name=PIPELINEID::${{ secrets.SIT_PIPELINEID}}"
  #         elif [[ "${{ github.base_ref }}" == *"uat" ]]; then
  #           echo "::set-output name=PIPELINEID::${{ secrets.UAT_PIPELINEID}}"
  #         elif [[ "${{ github.base_ref }}" == *"stage" ]]; then
  #           echo "::set-output name=PIPELINEID::${{ secrets.STAGE_PIPELINEID}}"
  #         fi
          
  dev-sync-deploy-verify-job: 
    needs: [initVariables]  
    uses: ./.github/workflows/sync-deploy-verify.yml
    with:
      BRANCH: dev
      PIPELINEID: ${{ secrets.DEV_PIPELINEID }}
      SHOULD_TRIGGER_PIPELINE: false
