name: sync-deploy-verify

on:
  workflow_call:
    outputs:
      BRANCH:
        description: "branch name"
        value: ${{ jobs.initJob.outputs.BRANCH}}
      
      SHOULD_TRIGGER_PIPELINE:
        description: "shoudl trigger a new deployment"
        value: ${{ jobs.initJob.outputs.SHOULD_TRIGGER_PIPELINE}}        
      
      VERIFY_URL:
        description: "Post deploy verify url"
        value: ${{ jobs.initJob.outputs.VERIFY_URL}}        
 
jobs:
  initJob:
    runs-on: ubuntu-latest
    outputs:
      SHOULD_TRIGGER_PIPELINE: ${{ steps.initVars.outputs.SHOULD_TRIGGER_PIPELINE}}
      BRANCH: ${{steps.initVars.outputs.BRANCH}}
      VERIFY_URL: ${{steps.initVars.outputs.VERIFY_URL}}
    steps:
    - name: initalize Inputs
      id: initVars
      run: |  
        echo ${{ github.ref }}
        echo ${{ github.ref_name }}
        echo ${{ github.event_name }}
        
        if [[ "${{ github.ref_name }}" == *"dev" ]]; then
          echo "::set-output name=BRANCH::dev"
          echo "::set-output name=SHOULD_TRIGGER_PIPELINE::false"
          echo "::set-output name=VERIFY_URL::http://dev.com"
        elif [[ "${{ github.ref_name }}" == *"sit" ]]; then
          echo "::set-output name=BRANCH::sit"
          echo "::set-output name=SHOULD_TRIGGER_PIPELINE::false"
          echo "::set-output name=VERIFY_URL::http://sit.com"
        elif [[ "${{ github.ref_name }}" == *"uat" ]]; then
          echo "::set-output name=BRANCH::uat"
          echo "::set-output name=SHOULD_TRIGGER_PIPELINE::false"
          echo "::set-output name=VERIFY_URL::http://uat.com"
        elif [[ "${{ github.ref_name }}" == *"stage" ]]; then
          echo "::set-output name=BRANCH::stage"
          echo "::set-output name=SHOULD_TRIGGER_PIPELINE::true"
          echo "::set-output name=VERIFY_URL::http://stage.com"
        fi

    - name: Print the outputs
      run: |
        echo "BRANCH: ${{steps.initVars.outputs.BRANCH}}"
        echo "SHOULD_TRIGGER_PIPELINE: ${{steps.initVars.outputs.SHOULD_TRIGGER_PIPELINE}}"
        echo "VERIFY_URL: ${{steps.initVars.outputs.VERIFY_URL}}"