name: Pipeline 

on:
  # push:
  #   branches: ['dev', 'uat', 'stage', 'main']  
  # pull_request:    
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        required: true
        type: environment

jobs:

  # initJob:
  #   uses: ./.github/workflows/initialize-inputs.yml

  sync-deploy-verify-job: 
    # needs: [initJob]  
    uses: ./.github/workflows/sync-deploy-verify.yml
    # with:
      # BRANCH: ${{ needs.initJob.outputs.BRANCH }}
      ENVIRONMENT: ${{ inputs.ENVIRONMENT }}      
      # SHOULD_TRIGGER_PIPELINE: ${{ needs.initJob.outputs.SHOULD_TRIGGER_PIPELINE }}  
      # VERIFY_URL: ${{ needs.initJob.outputs.VERIFY_URL }}
    secrets: inherit