
# This is a basic workflow to help you get started with Actions

name: Stage Pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: 
      - '*'
      - '!main'
 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  dev-sync-deploy-verify-job:
    if: github.ref == 'dev'
    uses: ./.github/workflows/sync-deploy-verify.yml
    with:
      BRANCH: dev
      PIPELINEID: "1234-dev"
      SHOULD_TRIGGER_PIPELINE: false
      
  sit-sync-deploy-verify-job:
    if: github.ref == 'sit'
    uses:  ./.github/workflows/sync-deploy-verify.yml
    with:
      BRANCH: sit
      PIPELINEID: "1234-sit"
      SHOULD_TRIGGER_PIPELINE: false
      
  stage-sync-deploy-verify-job:
    if: github.ref == 'stage'
    uses: ./.github/workflows/sync-deploy-verify.yml
    with:
      BRANCH: stage
      PIPELINEID: "1234-sit"
      SHOULD_TRIGGER_PIPELINE: true
      
  
      
