
# This is a basic workflow to help you get started with Actions

name: SIT PIpeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "sit" ]
  pull_request:
    branches: [ "sit" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    uses: ./.github/workflows/build-deploy-verify.yml
    with:
      BRANCH: sit
      PIPELINEID: "123-sit"
      SHOULD_TRIGGER_PIPELINE: true
