name: sync-deploy-verify

on:
  workflow_call:
    inputs:
      BRANCH:
        description: "branch name"
        type: string
        required: true
      
      SHOULD_TRIGGER_PIPELINE:
        description: "shoudl trigger a new deployment"
        type: string
        required: true        
      
      VERIFY_URL:
        description: "Post deploy verify url"
        type: string 
        required: true
      
 
jobs:
  SyncJob:
    runs-on: ubuntu-latest
    steps:
      - name: sync job
        run: |
          echo "sync job is done for ${{ inputs.BRANCH }}"
          
      - name: story board task
        if: ${{ inputs.BRANCH == 'dev' }}
        run: |
          echo "Should run only for Dev"
          echo ${{ github.ref_name }}
          
      - name: notiofication
        run: |
          echo "notiofication is done. Status: ${{ job.status }}" 
          
  DeployJob:
    needs: [SyncJob]
    runs-on: ubuntu-latest
    if: ${{ contains( fromJson('["dev", "sit"]'), github.ref_name) }}
    steps:
      - name: deploy
        run: |
          echo "PIPELINEID: ${{ secrets[format('{0}_PIPELINEID', inputs.BRANCH)] }} && SHOULD_TRIGGER_PIPELINE: ${{ inputs.SHOULD_TRIGGER_PIPELINE }}"
          
      - name: notification
        run: |
          echo "notification is done. Status: ${{ job.status }}"
          
  Verify:
    needs: [DeployJob]
    runs-on: ubuntu-latest
    steps:
      - name: verify
        run: |
          echo "verify url: ${{ inputs.VERIFY_URL }}"
          
      - name: notification
        run: |
          echo "notiofication is done. Status: ${{ job.status }}"
