name: Sync Job

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      BRANCH:
        description: "branch name"
        type: string
     
      
 
jobs:
  SyncJob:
    runs-on: ubuntu-latest
    steps:
      - name: sync job
        run: |
          echo "sync job is done for ${{ inputs.BRANCH }}"
          
      - name: notiofication
        run: |
          echo "notiofication is done. Status: ${{ job.status }}" 
